##七牛云的key
qiniu:
  accessKey:
  secretKey:
  bucketName:
  basePath:

## 百度推送
baidu:
  task:
    postUrl:
    baseUrl:

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: eumji-blog

#mynatis配置
mybatis:
  type-aliases-package: com.eumji.zblog.vo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml
#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file:
server:
  session-timeout : 3600
  port: 8080





